In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO

url = "https://finance.yahoo.com/quote/BTC-USD/history/?period1=1609459200&period2=1743465600&frequency=1mo"  # Replace with your actual URL

headers = {
    "User-Agent": "Mozilla/5.0"
}

# Get the page
page = requests.get(url, headers=headers)
soup = BeautifulSoup(page.text, 'html.parser')

# Find the div by its class
table_div = soup.find('div', class_='table-container yf-1jecxey')

# Print the content inside that div
table = table_div.find('table')
df = pd.read_html(StringIO(str(table)))[0]

# Rename the 6th column (index 5) and the column with "Close Close price adjusted for splits"
df.columns.values[4] = 'Close'
df.columns.values[5] = 'Adj Close'

# Display the DataFrame with the new column names
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
display(df)

,Date,Open,High,Low,Close,Adj Close,Volume
0,"Apr 1, 2025",82551.92,88466.95,74436.68,83404.84,83404.84,518610880629
1,"Mar 1, 2025",84373.87,95043.44,76624.25,82548.91,82548.91,1049435373908
2,"Feb 1, 2025",102402.80,102755.73,78248.91,84373.01,84373.01,1257276788562
3,"Jan 1, 2025",93425.10,109114.88,89260.10,102405.02,102405.02,1668843382017
4,"Dec 1, 2024",96461.34,108268.45,91317.13,93429.20,93429.20,2057355570135
5,"Nov 1, 2024",70216.90,99655.50,66803.65,96449.05,96449.05,2055808875264
6,"Oct 1, 2024",63335.61,73577.21,58895.21,70215.19,70215.19,993732418048
7,"Sep 1, 2024",58969.80,66480.70,52598.70,63329.50,63329.50,879117914822
8,"Aug 1, 2024",64625.84,65593.24,49121.24,58969.90,58969.90,1043105485208
9,"Jul 1, 2024",62673.61,69987.54,53717.38,64619.25,64619.25,953395573307
10,"Jun 1, 2024",67489.61,71907.85,58601.70,62678.29,62678.29,726773965644
11,"May 1, 2024",60609.50,71946.46,56555.29,67491.41,67491.41,874291509757
12,"Apr 1, 2024",71333.48,72715.36,59120.07,60636.86,60636.86,1016068331704
13,"Mar 1, 2024",61168.06,73750.07,59323.91,71333.65,71333.65,1446417844950
14,"Feb 1, 2024",42569.76,63913.13,41879.19,61198.38,61198.38,830721862621
15,"Jan 1, 2024",42280.23,48969.37,38521.89,42582.61,42582.61,825918941347
16,"Dec 1, 2023",37718.01,44705.52,37629.36,42265.19,42265.19,721704910480
17,"Nov 1, 2023",34657.27,38415.34,34133.44,37712.75,37712.75,570863267380
18,"Oct 1, 2023",26967.40,35150.43,26558.32,34667.78,34667.78,476425634860
19,"Sep 1, 2023",25934.02,27488.76,24930.30,26967.92,26967.92,337637313742
20,"Aug 1, 2023",29230.87,30176.80,25409.11,25931.47,25931.47,437724169499
21,"Jul 1, 2023",30471.85,31814.52,28934.29,29230.11,29230.11,382224489090
22,"Jun 1, 2023",27218.41,31389.54,24797.17,30477.25,30477.25,481734214225
23,"May 1, 2023",29227.10,29820.13,25878.43,27219.66,27219.66,443473015479
24,"Apr 1, 2023",28473.33,31005.61,27070.85,29268.81,29268.81,511540319004
25,"Mar 1, 2023",23150.93,29159.90,19628.25,28478.48,28478.48,883299703608
26,"Feb 1, 2023",23137.84,25134.12,21460.09,23147.35,23147.35,723968574897
27,"Jan 1, 2023",16547.91,23919.89,16521.23,23139.28,23139.28,690994018045
28,"Dec 1, 2022",17168.00,18318.53,16398.14,16547.50,16547.50,541356716034
29,"Nov 1, 2022",20494.90,21446.89,15599.05,17168.57,17168.57,1224531549126
30,"Oct 1, 2022",19431.11,20988.39,18319.82,20495.77,20495.77,957903424925
31,"Sep 1, 2022",20050.50,22673.82,18290.31,19431.79,19431.79,1123272250385
32,"Aug 1, 2022",23336.72,25135.59,19600.79,20049.76,20049.76,894192654543
33,"Jul 1, 2022",19820.47,24572.58,18966.95,23336.90,23336.90,927582363389
34,"Jun 1, 2022",31792.55,31957.29,17708.62,19784.73,19784.73,923939211678
35,"May 1, 2022",37713.27,39902.95,26350.49,31792.31,31792.31,1105689315990
36,"Apr 1, 2022",45554.16,47313.48,37697.94,37714.88,37714.88,830115888649
37,"Mar 1, 2022",43194.50,48086.84,37260.20,45538.68,45538.68,830943838435
38,"Feb 1, 2022",38481.77,45661.17,34459.22,43193.23,43193.23,671335993325
39,"Jan 1, 2022",46311.75,47881.41,33184.06,38483.13,38483.13,923979037681
40,"Dec 1, 2021",56907.96,59041.68,42874.62,46306.45,46306.45,957047184722
41,"Nov 1, 2021",61320.45,68789.63,53569.77,57005.43,57005.43,1053270271383
42,"Oct 1, 2021",43816.74,66930.39,43320.02,61318.96,61318.96,1153077903534
43,"Sep 1, 2021",47099.77,52853.77,39787.61,43790.89,43790.89,1102139678824
44,"Aug 1, 2021",41460.84,50482.08,37458.00,47166.69,47166.69,1014674184428
45,"Jul 1, 2021",35035.98,42235.55,29360.96,41626.20,41626.20,819103381204
46,"Jun 1, 2021",37293.79,41295.27,28893.62,35040.84,35040.84,1189647451707
47,"May 1, 2021",57714.66,59519.36,30681.50,37332.86,37332.86,1976593438572
48,"Apr 1, 2021",58926.56,64863.10,47159.48,57750.18,57750.18,1844481772417
49,"Mar 1, 2021",45159.50,61683.86,45115.09,58918.83,58918.83,1681184264687
50,"Feb 1, 2021",33114.58,58330.57,32384.23,45137.77,45137.77,2267152936675
51,"Jan 1, 2021",28994.01,41946.74,28722.76,33114.36,33114.36,2153473433571

In [4]:
df.to_csv('BTC-USD_data.csv', index=False)

In [6]:
import requests
import pandas as pd
from io import StringIO

url = "https://finance.yahoo.com/quote/TSLA/history/?period1=1609459200&period2=1743552000&frequency=1mo"
headers = {
    "User-Agent": "Mozilla/5.0"
}

# Get the page
response = requests.get(url, headers=headers)

# Wrap the HTML response in StringIO to avoid the warning
tables = pd.read_html(StringIO(response.text))


# The first table contains the historical data
df = tables[0]

# Optional: remove non-price rows like "Dividend" or "Stock Split"
df = df[~df['Open'].astype(str).str.contains("Dividend|Split", na=False)]

df.columns.values[4] = 'Close'
df.columns.values[5] = 'Adj Close'


# Display full table
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
display(df)

           Date    Open    High     Low   Close Adj Close      Volume
0   Apr 1, 2025  263.80  284.99  214.25  252.31    252.31  1561548600
1   Mar 1, 2025  300.34  303.94  217.02  259.16    259.16  2718957500
2   Feb 1, 2025  386.68  394.00  273.60  292.98    292.98  1581998600
3   Jan 1, 2025  390.10  439.74  373.04  404.60    404.60  1510656500
4   Dec 1, 2024  352.38  488.54  348.20  403.84    403.84  1903365900
5   Nov 1, 2024  252.04  361.93  238.88  345.16    345.16  2091913900
6   Oct 1, 2024  262.67  273.54  212.11  249.85    249.85  1910807800
7   Sep 1, 2024  215.26  264.86  209.64  261.63    261.63  1611273300
8   Aug 1, 2024  227.69  231.87  182.00  214.11    214.11  1618373100
9   Jul 1, 2024  201.02  271.00  200.85  232.07    232.07  2946114300
10  Jun 1, 2024  178.13  203.20  167.41  197.88    197.88  1407037300
11  May 1, 2024  182.00  187.56  167.75  178.08    178.08  1668180900
12  Apr 1, 2024  176.17  198.87  138.80  183.28    183.28  2478540800
13  Mar 1, 2024  200.52  204.52  160.51  175.79    175.79  1898904200
14  Feb 1, 2024  188.50  205.60  175.01  201.88    201.88  2019907700
15  Jan 1, 2024  250.08  251.25  180.06  187.29    187.29  2343784600
16  Dec 1, 2023  233.14  265.13  228.20  248.48    248.48  2294598400
17  Nov 1, 2023  204.04  252.75  197.85  240.08    240.08  2650798400
18  Oct 1, 2023  244.81  268.94  194.07  200.84    200.84  2590570100
19  Sep 1, 2023  257.26  278.98  234.58  250.22    250.22  2439306100
20  Aug 1, 2023  266.26  266.47  212.36  258.08    258.08  2501580900
21  Jul 1, 2023  276.49  299.29  254.12  267.43    267.43  2392089000
22  Jun 1, 2023  202.59  276.99  199.37  261.77    261.77  3440477900
23  May 1, 2023  163.17  204.48  158.83  203.93    203.93  2681994800
24  Apr 1, 2023  199.91  202.69  152.37  164.31    164.31  2505176300
25  Mar 1, 2023  206.21  207.79  163.91  207.46    207.46  3311619900
26  Feb 1, 2023  173.89  217.65  169.93  205.71    205.71  3624845100
27  Jan 1, 2023  118.47  180.68  101.81  173.22    173.22  3897499400
28  Dec 1, 2022  197.08  198.92  108.24  123.18    123.18  2944247700
29  Nov 1, 2022  234.05  237.40  166.19  194.70    194.70  1885275300
30  Oct 1, 2022  254.50  257.50  198.59  227.54    227.54  1735263100
31  Sep 1, 2022  272.58  313.80  262.47  265.25    265.25  1299271000
33  Aug 1, 2022  301.28  314.67  271.81  275.61    275.61  1695263200
34  Jul 1, 2022  227.00  298.32  216.17  297.15    297.15  1744884000
35  Jun 1, 2022  251.72  264.21  208.69  224.47    224.47  2011227900
36  May 1, 2022  286.92  318.50  206.86  252.75    252.75  1948221600
37  Apr 1, 2022  360.38  384.29  273.90  290.25    290.25  1520959800
38  Mar 1, 2022  289.89  371.59  252.01  359.20    359.20  1729272900
39  Feb 1, 2022  311.74  315.92  233.33  290.14    290.14  1391126700
40  Jan 1, 2022  382.58  402.67  264.00  312.24    312.24  1916006400
41  Dec 1, 2021  386.90  390.95  295.37  352.26    352.26  1530167700
42  Nov 1, 2021  381.67  414.50  326.20  381.59    381.59  1947334500
43  Oct 1, 2021  259.47  371.74  254.53  371.33    371.33  1586803800
44  Sep 1, 2021  244.69  266.33  236.28  258.49    258.49  1170513900
45  Aug 1, 2021  233.33  246.80  216.28  245.24    245.24  1143974700
46  Jul 1, 2021  227.97  233.33  206.82  229.07    229.07  1345349400
47  Jun 1, 2021  209.27  232.54  190.41  226.57    226.57  1559765700
48  May 1, 2021  234.60  235.33  182.33  208.41    208.41  1875527400
49  Apr 1, 2021  229.46  260.26  219.81  236.48    236.48  2035619100
50  Mar 1, 2021  230.04  240.37  179.83  222.64    222.64  2827357200
51  Feb 1, 2021  271.43  293.50  206.33  225.17    225.17  1568573700
52  Jan 1, 2021  239.82  300.13  239.06  264.51    264.51  2117084400

In [7]:
df.to_csv('TSLA_data.csv', index=False)

In [14]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO

url = "https://finance.yahoo.com/quote/AGG/history/?period1=1609459200&period2=1743552000&frequency=1mo"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

table_div = soup.find('div', class_='table-container')
table = table_div.find('table')

# Read the table as-is (without dropping anything)
df = pd.read_html(StringIO(str(table)))[0]

df.columns.values[4] = 'Close'
df.columns.values[5] = 'Adj Close'

# Display all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
display(df)

,Date,Open,High,Low,Close,Adj Close,Volume
0,"Apr 1, 2025",98.81,100.55,96.15,97.04,96.72,112931000
1,"Apr 1, 2025",0.33 Dividend,0.33 Dividend,0.33 Dividend,0.33 Dividend,0.33 Dividend,0.33 Dividend
2,"Mar 1, 2025",98.66,99.40,98.01,98.92,98.29,173294600
3,"Mar 3, 2025",0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend
4,"Feb 1, 2025",97.34,99.29,96.61,99.25,98.29,162617500
5,"Feb 3, 2025",0.32 Dividend,0.32 Dividend,0.32 Dividend,0.32 Dividend,0.32 Dividend,0.32 Dividend
6,"Jan 1, 2025",97.07,97.73,95.74,97.40,96.46,153162900
7,"Dec 18, 2024",0.32 Dividend,0.32 Dividend,0.32 Dividend,0.32 Dividend,0.32 Dividend,0.32 Dividend
8,"Dec 1, 2024",99.39,99.60,96.47,96.90,95.36,207807600
9,"Dec 2, 2024",0.31 Dividend,0.31 Dividend,0.31 Dividend,0.31 Dividend,0.31 Dividend,0.31 Dividend
10,"Nov 1, 2024",98.29,99.22,97.26,99.20,97.31,178516100
11,"Nov 1, 2024",0.31 Dividend,0.31 Dividend,0.31 Dividend,0.31 Dividend,0.31 Dividend,0.31 Dividend
12,"Oct 1, 2024",101.27,101.45,98.09,98.42,96.26,188422600
13,"Oct 1, 2024",0.31 Dividend,0.31 Dividend,0.31 Dividend,0.31 Dividend,0.31 Dividend,0.31 Dividend
14,"Sep 1, 2024",100.49,102.04,100.23,101.27,98.73,151200500
15,"Sep 3, 2024",0.31 Dividend,0.31 Dividend,0.31 Dividend,0.31 Dividend,0.31 Dividend,0.31 Dividend
16,"Aug 1, 2024",99.01,100.92,99.01,100.25,97.44,162159500
17,"Aug 1, 2024",0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend
18,"Jul 1, 2024",96.43,99.12,96.22,99.11,96.03,156329800
19,"Jul 1, 2024",0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend
20,"Jun 1, 2024",96.40,98.05,96.38,97.07,93.76,116832100
21,"Jun 3, 2024",0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend
22,"May 1, 2024",95.20,97.28,94.99,96.52,92.94,142883000
23,"May 1, 2024",0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend,0.30 Dividend
24,"Apr 1, 2024",97.32,97.34,94.85,95.23,91.43,225145700
25,"Apr 1, 2024",0.29 Dividend,0.29 Dividend,0.29 Dividend,0.29 Dividend,0.29 Dividend,0.29 Dividend
26,"Mar 1, 2024",96.99,98.41,96.81,97.94,93.75,171183600
27,"Mar 1, 2024",0.29 Dividend,0.29 Dividend,0.29 Dividend,0.29 Dividend,0.29 Dividend,0.29 Dividend
28,"Feb 1, 2024",99.20,99.57,96.75,97.35,92.91,183195100
29,"Feb 1, 2024",0.29 Dividend,0.29 Dividend,0.29 Dividend,0.29 Dividend,0.29 Dividend,0.29 Dividend
30,"Jan 1, 2024",98.84,99.36,97.67,99.10,94.58,189449700
31,"Dec 14, 2023",0.28 Dividend,0.28 Dividend,0.28 Dividend,0.28 Dividend,0.28 Dividend,0.28 Dividend
32,"Dec 1, 2023",96.00,99.70,95.97,99.25,94.19,200149800
33,"Dec 1, 2023",0.27 Dividend,0.27 Dividend,0.27 Dividend,0.27 Dividend,0.27 Dividend,0.27 Dividend
34,"Nov 1, 2023",92.23,96.67,92.23,96.26,91.08,189882200
35,"Nov 1, 2023",0.28 Dividend,0.28 Dividend,0.28 Dividend,0.28 Dividend,0.28 Dividend,0.28 Dividend
36,"Oct 1, 2023",93.43,94.05,91.58,92.31,87.10,217450300
37,"Oct 2, 2023",0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend
38,"Sep 1, 2023",96.54,96.57,93.53,94.04,88.49,156122000
39,"Sep 1, 2023",0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend
40,"Aug 1, 2023",97.01,97.22,95.04,96.80,90.84,189197000
41,"Aug 1, 2023",0.27 Dividend,0.27 Dividend,0.27 Dividend,0.27 Dividend,0.27 Dividend,0.27 Dividend
42,"Jul 1, 2023",97.82,98.48,96.28,97.68,91.43,147772000
43,"Jul 3, 2023",0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend
44,"Jun 1, 2023",98.60,98.80,97.45,97.95,91.44,154341400
45,"Jun 1, 2023",0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend
46,"May 1, 2023",99.35,100.42,97.24,98.57,91.79,147935400
47,"May 1, 2023",0.25 Dividend,0.25 Dividend,0.25 Dividend,0.25 Dividend,0.25 Dividend,0.25 Dividend
48,"Apr 1, 2023",99.28,100.98,98.71,99.96,92.85,102268700
49,"Apr 3, 2023",0.25 Dividend,0.25 Dividend,0.25 Dividend,0.25 Dividend,0.25 Dividend,0.25 Dividend
50,"Mar 1, 2023",96.83,100.49,96.11,99.64,92.33,178250900
51,"Mar 1, 2023",0.23 Dividend,0.23 Dividend,0.23 Dividend,0.23 Dividend,0.23 Dividend,0.23 Dividend
52,"Feb 1, 2023",100.19,101.15,96.93,97.31,89.95,136172900
53,"Feb 1, 2023",0.25 Dividend,0.25 Dividend,0.25 Dividend,0.25 Dividend,0.25 Dividend,0.25 Dividend
54,"Jan 1, 2023",97.97,100.88,97.37,100.22,92.64,163155500
55,"Dec 15, 2022",0.23 Dividend,0.23 Dividend,0.23 Dividend,0.23 Dividend,0.23 Dividend,0.23 Dividend
56,"Dec 1, 2022",98.30,100.18,96.97,96.99,89.25,182228100
57,"Dec 1, 2022",0.23 Dividend,0.23 Dividend,0.23 Dividend,0.23 Dividend,0.23 Dividend,0.23 Dividend
58,"Nov 1, 2022",95.25,98.32,93.93,98.29,90.24,151586500
59,"Nov 1, 2022",0.22 Dividend,0.22 Dividend,0.22 Dividend,0.22 Dividend,0.22 Dividend,0.22 Dividend
60,"Oct 1, 2022",96.89,97.55,93.20,94.90,86.94,156647200
61,"Oct 3, 2022",0.21 Dividend,0.21 Dividend,0.21 Dividend,0.21 Dividend,0.21 Dividend,0.21 Dividend
62,"Sep 1, 2022",100.07,100.67,95.38,96.34,88.08,167483600
63,"Sep 1, 2022",0.20 Dividend,0.20 Dividend,0.20 Dividend,0.20 Dividend,0.20 Dividend,0.20 Dividend
64,"Aug 1, 2022",103.99,104.35,100.64,100.71,91.89,137148700
65,"Aug 1, 2022",0.20 Dividend,0.20 Dividend,0.20 Dividend,0.20 Dividend,0.20 Dividend,0.20 Dividend
66,"Jul 1, 2022",102.21,104.40,101.16,104.07,94.79,129139000
67,"Jul 1, 2022",0.19 Dividend,0.19 Dividend,0.19 Dividend,0.19 Dividend,0.19 Dividend,0.19 Dividend
68,"Jun 1, 2022",103.39,103.53,98.86,101.68,92.44,164197600
69,"Jun 1, 2022",0.19 Dividend,0.19 Dividend,0.19 Dividend,0.19 Dividend,0.19 Dividend,0.19 Dividend
70,"May 1, 2022",102.32,104.31,101.48,103.47,93.90,209531300
71,"May 2, 2022",0.18 Dividend,0.18 Dividend,0.18 Dividend,0.18 Dividend,0.18 Dividend,0.18 Dividend
72,"Apr 1, 2022",106.35,106.95,102.67,102.87,93.22,186590100
73,"Apr 1, 2022",0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend
74,"Mar 1, 2022",110.60,111.17,105.98,107.10,96.91,263297700
75,"Mar 1, 2022",0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend
76,"Feb 1, 2022",111.66,111.97,109.10,110.36,99.72,182615900
77,"Feb 1, 2022",0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend
78,"Jan 1, 2022",113.67,113.68,111.36,111.80,101.02,177044400
79,"Dec 16, 2021",0.12 Dividend,0.12 Dividend,0.12 Dividend,0.12 Dividend,0.12 Dividend,0.12 Dividend
80,"Dec 1, 2021",114.27,115.24,113.81,114.08,102.83,168251800
81,"Dec 1, 2021",0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend
82,"Nov 1, 2021",114.16,115.50,113.39,114.77,103.29,143895100
83,"Nov 1, 2021",0.18 Dividend,0.18 Dividend,0.18 Dividend,0.18 Dividend,0.18 Dividend,0.18 Dividend
84,"Oct 1, 2021",114.82,115.06,113.84,114.64,103.01,116295700
85,"Oct 1, 2021",0.18 Dividend,0.18 Dividend,0.18 Dividend,0.18 Dividend,0.18 Dividend,0.18 Dividend
86,"Sep 1, 2021",116.02,116.38,114.69,114.83,103.03,105451600
87,"Sep 1, 2021",0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend
88,"Aug 1, 2021",116.36,116.83,115.34,116.06,103.99,109572100
89,"Aug 2, 2021",0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend
90,"Jul 1, 2021",115.15,116.82,115.01,116.46,104.20,125908500
91,"Jul 1, 2021",0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend
92,"Jun 1, 2021",114.36,115.45,113.97,115.33,103.04,124146500
93,"Jun 1, 2021",0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend
94,"May 1, 2021",114.40,114.97,113.78,114.55,102.19,108440300
95,"May 3, 2021",0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend
96,"Apr 1, 2021",113.93,115.13,113.69,114.49,101.98,113892400
97,"Apr 1, 2021",0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend,0.17 Dividend
98,"Mar 1, 2021",114.97,115.59,113.20,113.83,101.23,152163600
99,"Mar 1, 2021",0.19 Dividend,0.19 Dividend,0.19 Dividend,0.19 Dividend,0.19 Dividend,0.19 Dividend
100,"Feb 1, 2021",117.20,117.26,114.20,115.34,102.40,113958700
101,"Feb 1, 2021",0.19 Dividend,0.19 Dividend,0.19 Dividend,0.19 Dividend,0.19 Dividend,0.19 Dividend
102,"Jan 1, 2021",118.08,118.14,116.56,117.31,104.15,129574500

In [15]:
df.to_csv('../Total_Data/AGG_data.csv', index=False)

In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO

# Yahoo Finance historical data for BIL
url = "https://finance.yahoo.com/quote/BIL/history/?period1=1609459200&period2=1743552000&frequency=1mo"

headers = {
    "User-Agent": "Mozilla/5.0"
}

# Request page content
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

# Locate the table
table_div = soup.find('div', class_='table-container')
table = table_div.find('table')

# Read HTML table as-is
df = pd.read_html(StringIO(str(table)))[0]

df.columns.values[4] = 'Close'
df.columns.values[5] = 'Adj Close'

# Show full table without dropping/modifying anything
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
display(df)

,Date,Open,High,Low,Close,Adj Close,Volume
0,"Apr 1, 2025",91.43,91.56,91.42,91.56,91.24,226444200
1,"Apr 1, 2025",0.32 Dividend,0.32 Dividend,0.32 Dividend,0.32 Dividend,0.32 Dividend,0.32 Dividend
2,"Mar 1, 2025",91.45,91.74,91.44,91.73,91.12,278655900
3,"Mar 3, 2025",0.29 Dividend,0.29 Dividend,0.29 Dividend,0.29 Dividend,0.29 Dividend,0.29 Dividend
4,"Feb 1, 2025",91.45,91.73,91.44,91.72,90.79,152321000
5,"Feb 3, 2025",0.33 Dividend,0.33 Dividend,0.33 Dividend,0.33 Dividend,0.33 Dividend,0.33 Dividend
6,"Jan 1, 2025",91.45,91.76,91.44,91.75,90.82,157312600
7,"Dec 19, 2024",0.38 Dividend,0.38 Dividend,0.38 Dividend,0.38 Dividend,0.38 Dividend,0.38 Dividend
8,"Dec 1, 2024",91.47,91.67,91.29,91.43,89.79,155048200
9,"Dec 2, 2024",0.34 Dividend,0.34 Dividend,0.34 Dividend,0.34 Dividend,0.34 Dividend,0.34 Dividend
10,"Nov 1, 2024",91.48,91.80,91.47,91.78,89.78,150196500
11,"Nov 1, 2024",0.36 Dividend,0.36 Dividend,0.36 Dividend,0.36 Dividend,0.36 Dividend,0.36 Dividend
12,"Oct 1, 2024",91.46,91.80,91.45,91.80,89.44,140940000
13,"Oct 1, 2024",0.37 Dividend,0.37 Dividend,0.37 Dividend,0.37 Dividend,0.37 Dividend,0.37 Dividend
14,"Sep 1, 2024",91.77,91.82,91.44,91.81,89.07,156932000
15,"Sep 3, 2024",0.40 Dividend,0.40 Dividend,0.40 Dividend,0.40 Dividend,0.40 Dividend,0.40 Dividend
16,"Aug 1, 2024",91.41,91.83,91.41,91.82,88.68,192025600
17,"Aug 1, 2024",0.40 Dividend,0.40 Dividend,0.40 Dividend,0.40 Dividend,0.40 Dividend,0.40 Dividend
18,"Jul 1, 2024",91.42,91.80,91.41,91.80,88.29,138514400
19,"Jul 1, 2024",0.39 Dividend,0.39 Dividend,0.39 Dividend,0.39 Dividend,0.39 Dividend,0.39 Dividend
20,"Jun 1, 2024",91.45,91.79,91.43,91.78,87.88,117206200
21,"Jun 3, 2024",0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend
22,"May 1, 2024",91.43,91.83,91.42,91.82,87.54,139772400
23,"May 1, 2024",0.39 Dividend,0.39 Dividend,0.39 Dividend,0.39 Dividend,0.39 Dividend,0.39 Dividend
24,"Apr 1, 2024",91.42,91.80,91.42,91.79,87.13,165486700
25,"Apr 1, 2024",0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend
26,"Mar 1, 2024",91.44,91.81,91.44,91.80,86.80,121886400
27,"Mar 1, 2024",0.36 Dividend,0.36 Dividend,0.36 Dividend,0.36 Dividend,0.36 Dividend,0.36 Dividend
28,"Feb 1, 2024",91.42,91.79,91.42,91.78,86.40,136273300
29,"Feb 1, 2024",0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend
30,"Jan 1, 2024",91.40,91.79,91.40,91.78,86.40,156412100
31,"Dec 18, 2023",0.42 Dividend,0.42 Dividend,0.42 Dividend,0.42 Dividend,0.42 Dividend,0.42 Dividend
32,"Dec 1, 2023",91.45,91.63,91.21,91.39,85.25,160903300
33,"Dec 1, 2023",0.42 Dividend,0.42 Dividend,0.42 Dividend,0.42 Dividend,0.42 Dividend,0.42 Dividend
34,"Nov 1, 2023",91.44,91.85,91.43,91.84,85.29,229526700
35,"Nov 1, 2023",0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend
36,"Oct 1, 2023",91.45,91.83,91.44,91.82,84.90,270208000
37,"Oct 2, 2023",0.39 Dividend,0.39 Dividend,0.39 Dividend,0.39 Dividend,0.39 Dividend,0.39 Dividend
38,"Sep 1, 2023",91.47,91.83,91.46,91.82,84.53,161819200
39,"Sep 1, 2023",0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend,0.41 Dividend
40,"Aug 1, 2023",91.43,91.86,91.42,91.86,84.20,151286000
41,"Aug 1, 2023",0.39 Dividend,0.39 Dividend,0.39 Dividend,0.39 Dividend,0.39 Dividend,0.39 Dividend
42,"Jul 1, 2023",91.46,91.81,91.46,91.80,83.80,109308900
43,"Jul 3, 2023",0.37 Dividend,0.37 Dividend,0.37 Dividend,0.37 Dividend,0.37 Dividend,0.37 Dividend
44,"Jun 1, 2023",91.45,91.83,91.44,91.82,83.48,139963000
45,"Jun 1, 2023",0.37 Dividend,0.37 Dividend,0.37 Dividend,0.37 Dividend,0.37 Dividend,0.37 Dividend
46,"May 1, 2023",91.44,91.78,91.41,91.77,83.12,146814900
47,"May 1, 2023",0.35 Dividend,0.35 Dividend,0.35 Dividend,0.35 Dividend,0.35 Dividend,0.35 Dividend
48,"Apr 1, 2023",91.48,91.79,91.47,91.78,82.79,134371500
49,"Apr 3, 2023",0.37 Dividend,0.37 Dividend,0.37 Dividend,0.37 Dividend,0.37 Dividend,0.37 Dividend
50,"Mar 1, 2023",91.47,91.85,91.46,91.82,82.60,228427800
51,"Mar 1, 2023",0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend
52,"Feb 1, 2023",91.42,91.71,91.40,91.71,82.19,145839100
53,"Feb 1, 2023",0.34 Dividend,0.34 Dividend,0.34 Dividend,0.34 Dividend,0.34 Dividend,0.34 Dividend
54,"Jan 1, 2023",91.48,91.74,91.47,91.73,82.21,139453300
55,"Dec 19, 2022",0.27 Dividend,0.27 Dividend,0.27 Dividend,0.27 Dividend,0.27 Dividend,0.27 Dividend
56,"Dec 1, 2022",91.43,91.60,91.33,91.47,81.50,142210000
57,"Dec 1, 2022",0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend,0.26 Dividend
58,"Nov 1, 2022",91.41,91.67,91.39,91.67,81.50,125073900
59,"Nov 1, 2022",0.21 Dividend,0.21 Dividend,0.21 Dividend,0.21 Dividend,0.21 Dividend,0.21 Dividend
60,"Oct 1, 2022",91.45,91.61,91.42,91.59,81.29,133207400
61,"Oct 3, 2022",0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend,0.16 Dividend
62,"Sep 1, 2022",91.43,91.60,91.42,91.60,81.17,133691600
63,"Sep 1, 2022",0.14 Dividend,0.14 Dividend,0.14 Dividend,0.14 Dividend,0.14 Dividend,0.14 Dividend
64,"Aug 1, 2022",91.37,91.55,91.37,91.55,81.04,138793300
65,"Aug 1, 2022",0.10 Dividend,0.10 Dividend,0.10 Dividend,0.10 Dividend,0.10 Dividend,0.10 Dividend
66,"Jul 1, 2022",91.43,91.48,91.40,91.47,80.93,138228900
67,"Jul 1, 2022",0.05 Dividend,0.05 Dividend,0.05 Dividend,0.05 Dividend,0.05 Dividend,0.05 Dividend
68,"Jun 1, 2022",91.44,91.49,91.41,91.49,80.92,127557600
69,"Jun 1, 2022",0.03 Dividend,0.03 Dividend,0.03 Dividend,0.03 Dividend,0.03 Dividend,0.03 Dividend
70,"May 1, 2022",91.44,91.48,91.42,91.45,80.88,123245200
71,"Apr 1, 2022",91.42,91.44,91.41,91.42,80.85,76053100
72,"Mar 1, 2022",0.02 Dividend,0.02 Dividend,0.02 Dividend,0.02 Dividend,0.02 Dividend,0.02 Dividend
73,"Mar 1, 2022",91.42,91.43,91.40,91.43,80.84,90882500
74,"Feb 1, 2022",91.41,91.43,91.40,91.41,80.83,90521300
75,"Jan 1, 2022",91.43,91.43,91.41,91.43,80.84,74430900
76,"Dec 1, 2021",91.44,91.44,91.42,91.43,80.84,25722900
77,"Nov 1, 2021",91.44,91.45,91.43,91.43,80.84,21169800
78,"Oct 1, 2021",91.46,91.46,91.43,91.45,80.86,18012100
79,"Sep 1, 2021",91.46,91.47,91.44,91.46,80.87,31234700
80,"Aug 1, 2021",91.46,91.47,91.45,91.45,80.86,20429900
81,"Jul 1, 2021",91.47,91.48,91.46,91.46,80.87,19782500
82,"Jun 1, 2021",91.48,91.49,91.47,91.47,80.88,19359400
83,"May 1, 2021",91.49,91.50,91.48,91.49,80.90,26742000
84,"Apr 1, 2021",91.51,91.51,91.49,91.50,80.91,25681800
85,"Mar 1, 2021",91.51,91.51,91.50,91.50,80.91,24587200
86,"Feb 1, 2021",91.52,91.53,91.50,91.51,80.91,22015300
87,"Jan 1, 2021",91.52,91.52,91.51,91.52,80.92,37019000

In [11]:
df.to_csv('BIL_data.csv', index=False)